name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "DOCKER_USERNAME: $DOCKER_USERNAME"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
          echo "First 4 characters of DOCKER_PASSWORD: ${DOCKER_PASSWORD:0:4}"
      - name: Login to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - name: Build Docker image
        run: docker build -t your-image-name .
      - name: Push Docker image
        run: docker push your-image-name
